import domManipulation from './dom';
import dom from './dom';
import './styles.css';
import rain from './asset/rain.png';
import humidity from './asset/humidity.png';
import wind from './asset/wind.png';
import clouds from './asset/clouds.png';
import clear from './asset/clear.png';
import drizzle from './asset/drizzle.png';
import mist from './asset/mist.png';
import snow from './asset/snow.png';
